//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonsDenAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DragonsDen2Entities : DbContext
    {
        public DragonsDen2Entities()
            : base("name=DragonsDen2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PM_Models> PM_Models { get; set; }
        public virtual DbSet<wt_binary_prediction2> wt_binary_prediction2 { get; set; }
    }
}
