//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonsDenAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_Models
    {
        public string model_name { get; set; }
        public byte[] model { get; set; }
    }
}
