//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonsDenAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class wt_binary_prediction2
    {
        public int id { get; set; }
        public Nullable<int> test_id { get; set; }
        public Nullable<int> cycle { get; set; }
        public Nullable<double> Forest_Probability { get; set; }
        public string Forest_Prediction { get; set; }
        public Nullable<double> Boosted_Probability { get; set; }
        public string Boosted_Prediction { get; set; }
        public Nullable<double> Logistic_Probability { get; set; }
        public string Logistic_Prediction { get; set; }
        public Nullable<double> Nnet_Probability { get; set; }
        public string Nnet_Prediction { get; set; }
    }
}
